### ISSUE TITLE
@Autowired class is null inside Rule class

### ISSUE THREAD

**Issue by madhuram2468** [EasyRules/easyrules#51]
Hi,

Thanks for this awesome feature. It made my life easier, when I was thinking how to implement multiple rules in my project.
I have a scenario where I update my database based on conditions. I am using EasyRules for the same.

I am autowiring my DAO class inside the spring rule engine class.
When I run the code, my Dao class which is autowired inside my SpringRule class is null. Hence I am getting nullpointerexception.
My code is as below

```java
@SpringRule
public class Rule1 {

@Autowired
private MyDAO myDAO;   --> (is null during runtime)

public Rule1 () {
    super();
}

@Condition
public boolean when() {
    if (condition) {
        return true;
    }
    return false;
}

@Action(order = 1)
public void then() throws Exception {
    myDAO.update("test");
    System.out.println("Waiting state success");
}

}
```

My DAO interface is:

```java
public interface MyDAO {
   public void update(String value);
}
```

My DAO impl calss is:

```java
@Repository
public class MyDAOImpl implements MyDAO{

@Override
public void update(String value){
//update in DB
}
}
```

**Comment by benas** [comment]
Hi, thank you.

Is your spring rule managed by spring?
If yes, then dependency injection should work for the rule.

Kind regards
Mahmoud

**Comment by madhuram2468** [comment]
Thanks for the response.

Yes I am managing my rules by spring. 

My spring context is as below:

<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.springframework.org/schema/beans" xmlns:mvc="http://www.springframework.org/schema/mvc"
	xmlns:util="http://www.springframework.org/schema/util" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:security="http://www.springframework.org/schema/security"
	xsi:schemaLocation="
            http://www.springframework.org/schema/beans     http://www.springframework.org/schema/beans/spring-beans.xsd
            http://www.springframework.org/schema/util    http://www.springframework.org/schema/util/spring-util.xsd
            http://www.springframework.org/schema/context   http://www.springframework.org/schema/context/spring-context.xsd
            http://www.springframework.org/schema/mvc       http://www.springframework.org/schema/mvc/spring-mvc.xsd
            http://www.springframework.org/schema/tx        http://www.springframework.org/schema/tx/spring-tx.xsd
             http://www.springframework.org/schema/security
                            http://www.springframework.org/schema/security/spring-security-4.0.xsd">

        <mvc:annotation-driven /> 
	<context:annotation-config />
	<mvc:default-servlet-handler />
	<context:component-scan base-package="com.test.*" />

        <beans:bean
		class="org.springframework.web.servlet.view.InternalResourceViewResolver">
		<beans:property name="prefix" value="/WEB-INF/views/" />
		<beans:property name="suffix" value=".jsp" />
	</beans:bean>

      <bean id="rulesEngine" class="org.easyrules.spring.RulesEngineFactoryBean">
		<property name="rules">
			<list>
			</list>
		</property>
	</bean>
  </beans>

Please let me know if I have missed something

**Comment by tledwar** [comment]
I am pretty much having the same issue (end result is a null pointer exception caught by the rule engine). Basically would expect to autowire in the Repository and make the proper calls to it in the Action. Sounds like something fairly common a user may like to do.

So far I have tried it with @SpringRule and with just @Rule. Basic difference should just be the scope being prototype I believe. In both cases the @Autowire'd items were null. 

I do see some similar issues with Autowire in other forums and I am continuing to investigate.

**Comment by benas** [comment]
Hi,

Thank you for reporting this! will look into this asap.

Kind regards
Mahmoud

**Comment by tledwar** [comment]
I would like to state I have worked through my issues. First problem is conversion from XML to Java Config using examples at your site and of course my own experience level. I will try to provide details for others below. BTW, I use Spring Boot to even complicate (or improve) things more.

My first mistake was not using 
    @Autowired
    private ApplicationContext context;
and
    RulesEngine rulesEngine = (RulesEngine) context.getBean("rulesEngine");
to get the context for the application and create the rules engine. I was previously creating a rules engine by calling aNewRulesEngine. 

I made this mistake because I was treating your context usage examples as needed with the XML configuration. My BIG mistake and I have now learned more than I need to detail here.

Second issue was registration of the rules themselves.
    rulesEngine.registerRule(new DummyRule());
    rulesEngine.registerRule(new MyNewRule(claim));
Using new basically disables the @Autowired functionality provided by Spring and is documented in their documentation. 

So, back to using contexts properly:
    rulesEngine.registerRule(context.getBean(DummyRule.class));
    rulesEngine.registerRule(context.getBean(MyNewRule.class, claim, userID));

The first one is from your documentation and tutorials. The second one is where I was challenged with @Autowired and I wanted to show it here as a more advanced usage. Claim is an object pulled from the database and passed to the class in the Constructor of the Rule. The userID is also passed as a parameter to be used.

I have provided the shell of Class below. It shows the auto wiring, use of a database repository and passing parameters through the constructor. I am hopeful my experience with this can help this issue and maybe the linked issue. Or at least help others get on the right track to resolve their unique situation.

package com.foobar.rulesprocessor.rules;

import java.time.LocalDate;
import javax.sql.DataSource;

import org.easyrules.annotation.Action;
import org.easyrules.annotation.Condition;
import org.easyrules.spring.SpringRule;

import org.springframework.beans.factory.annotation.Autowired;

import com.healthcloud.rulesprocessor.model.Claim;
import com.healthcloud.rulesprocessor.model.Message;
import com.healthcloud.rulesprocessor.repository.MessageRepository;

@SpringRule
public class MyNewRule {
	@Autowired
	private MessageRepository messageRepository;

	private Claim claim;
	private Long userID;
	
        public MyNewRule(Claim claim, Long id) {
		this.claim = claim;
		this.userID = id;
	}

	@Condition
        public boolean when() {
        .... condition logic goes here .... 
    }

    @Action
    public void then(){
        Message message = new Message();
        message.setSubject(claim.getClientCode() + " A Special Message Subject");
        message.setText("The text of the message");
        message.setUserId(this.userID);
        message = messageRepository.save(message);     
    }
}

**Comment by benas** [comment]
@madhuram2468 

Looking at your spring config, I see you are configuring your rules via annotations and your engine with xml using the `RuleEngineFactoryBean` but with an empty rules list:

```xml
<bean id="rulesEngine" class="org.easyrules.spring.RulesEngineFactoryBean">
    <property name="rules">
        <list>
        </list>
    </property>
</bean>
```

if you get the rules engine from the context, there would be no registered rules in it.

I suggest to configure your rule in xml and add it to the list of rules in the engine.

**Comment by benas** [comment]
When you choose to use spring to configure your rules, you don't have to register them explicitly. The factory bean will set them in the rules engine at construction time. The spring tutorial was confusing, sorry about that.

All you have to do is to get a reference to the rules engine and fire rules.
Please take a look at the [updated tutorial](http://www.easyrules.org/tutorials/spring-tutorial.html).

**Comment by benas** [comment]
@madhuram2468  Any update on this?

**Comment by benas** [comment]
Hi @madhuram2468, @tledwar

After re-reading this thread, I thought it would be helpful to give an example of each type of spring configuration.
The tricky part is related to how and when rules are registered in the rules engine.
I will make this explicit for each example.

### Annotation config:

```java
@Component
public class DAO {

    public void save(String input) {
        System.out.println(input + " saved to db");
    }

}

@SpringRule
public class DummyRule {

    @Autowired
    private DAO dao;

    @Condition
    public boolean when() {
        return true;
    }

    @Action
    public void then(){
        dao.save("foo");
        System.out.println("Hey, I'm managed by Spring");
    }
}

public class Launcher {

    public static void main(String[] args) throws Exception {
        ApplicationContext context = new AnnotationConfigApplicationContext("org.easyrules.samples.spring");
        DummyRule dummyRule = context.getBean(DummyRule.class);

        RulesEngine rulesEngine = RulesEngineBuilder.aNewRulesEngine().build();
        rulesEngine.registerRule(dummyRule);
        rulesEngine.fireRules();
    }

}
```

### XML config

```java
public class DAO {

    public void save(String input) {
        System.out.println(input + " saved to db");
    }

}

@Rule
public class DummyRule {

    private DAO dao;

    public DummyRule(DAO dao) {
        this.dao = dao;
    }

    @Condition
    public boolean when() {
        return true;
    }

    @Action
    public void then(){
        dao.save("foo");
        System.out.println("Hey, I'm managed by Spring");
    }
}

public class Launcher {

    public static void main(String[] args) throws Exception {
        ApplicationContext context = new ClassPathXmlApplicationContext("org/easyrules/samples/spring/application-context.xml");
        RulesEngine rulesEngine = (RulesEngine) context.getBean("rulesEngine");

        rulesEngine.fireRules();
    }

}
```

```xml
    <bean id="dao" class="org.easyrules.samples.spring.DAO"/>

    <!-- configure rule  -->
    <bean id="rule" class="org.easyrules.samples.spring.DummyRule">
        <constructor-arg ref="dao"/>
    </bean>

    <!-- configure rules engine -->
    <bean id="rulesEngine" class="org.easyrules.spring.RulesEngineFactoryBean">
        <property name="rules">
            <list>
                <ref bean="rule"/>
            </list>
        </property>
    </bean>
```

### Java config

```java
public class DAO {

    public void save(String input) {
        System.out.println(input + " saved to db");
    }

}


@Rule
public class DummyRule {

    private DAO dao;

    public DummyRule(DAO dao) {
        this.dao = dao;
    }

    @Condition
    public boolean when() {
        return true;
    }

    @Action
    public void then(){
        dao.save("foo");
        System.out.println("Hey, I'm managed by Spring");
    }
}

@Configuration
public class Launcher {

    @Bean
    public DAO dao() {
        return new DAO();
    }

    @Bean
    public DummyRule rule() {
        return new DummyRule(dao());
    }

    @Bean
    public RulesEngine rulesEngine() {
        RulesEngineFactoryBean rulesEngineFactoryBean = new RulesEngineFactoryBean();
        rulesEngineFactoryBean.setRules(Arrays.<Object>asList(rule()));
        return rulesEngineFactoryBean.getObject();
    }

    public static void main(String[] args) throws Exception {
        ApplicationContext context = new AnnotationConfigApplicationContext("org.easyrules.samples.spring");
        RulesEngine rulesEngine = (RulesEngine) context.getBean("rulesEngine");

        rulesEngine.fireRules();
    }

}
```

To sum up:

* Xml config: no need to register rules, the `RulesEngineFactoryBean` does this. We need to get the rules engine from spring context and fire rules.
The major advantage is the ability to add/remove rules without recompiling the app.

* Annotation config: Rules ara managed by spring (so the autowiring with annotations works) but not the engine. We still need to create the engine and register rules explicitly.
This is because it is not possible to register rules **decalratively** with annotations.

* Java config: Either use the factory bean to set rules, or create the rules engine with the builder and set rules explicitly.


When I run these 3 examples, I get:

```
foo saved to db
Hey, I'm managed by Spring
```

I have no NullPointerException which mean the autowiring seems to work.

Sorry if the tutorial was confusing (I have updated it) and I hope these examples are helpful.

Please tet me know if this helped.
Kind regards

**Comment by madhuram2468** [comment]
@benas 
Sorry for the late reply.

The solution works fine. I followed the updated tutorial and the autowiring issue is now resolved.

Thanks a lot for your help.

**Comment by careerscale** [comment]
@benas , I do not see @SpringRule working,

I keep getting this error 
java.lang.IllegalArgumentException: Rule 'com.mycompany.mlm.rules.BusinessLeaderRule$$EnhancerBySpringCGLIB$$8ba6eda2' is not annotated with 'org.easyrules.annotation.Rule'
	at org.easyrules.core.RuleDefinitionValidator.checkRuleClass(RuleDefinitionValidator.java:55) ~[easyrules-core-2.4.0.jar:?]
	at org.easyrules.core.RuleDefinitionValidator.validateRuleDefinition(RuleDefinitionValidator.java:47) ~[easyrules-core-2.4.0.jar:?]
	at org.easyrules.core.RuleProxy.asRule(RuleProxy.java:59) ~[easyrules-core-2.4.0.jar:?]
	at org.easyrules.core.DefaultRulesEngine.registerRule(DefaultRulesEngine.java:81) ~[easyrules-core-2.4.0.jar:?]
	at com.mycompany.mlm.service.internal.VolumeServiceImpl.updateVolumes(VolumeServiceImpl.java:176) [mlm-core-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at com.mycompany.mlm.audit.ApplicationAuditor.serviceMethodExecutionTime(ApplicationAuditor.java:42) [mlm-core-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at com.sun.proxy.$Proxy144.updateVolumes(Unknown Source) [?:?]
	at com.callidus.mlm.resource.OrderResource.processOrder(OrderResource.java:61) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) [spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116) [spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) [spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) [spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) [spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) [spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) [spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) [javax.servlet-3.0.0.v201112011016.jar:?]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [javax.servlet-3.0.0.v201112011016.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) [jetty-servlet-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496) [jetty-servlet-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.11.jar:8.5.11]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467) [jetty-servlet-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467) [jetty-servlet-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:115) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.web.support.ErrorPageFilter.access$000(ErrorPageFilter.java:59) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.web.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:90) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:108) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467) [jetty-servlet-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501) [jetty-servlet-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557) [jetty-security-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) [jetty-server-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429) [jetty-servlet-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) [jetty-server-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255) [jetty-server-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154) [jetty-server-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.server.Server.handle(Server.java:370) [jetty-server-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494) [jetty-server-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982) [jetty-server-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043) [jetty-server-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) [jetty-http-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [jetty-http-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696) [jetty-io-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53) [jetty-io-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-8.1.16.v20140903.jar:8.1.16.v20140903]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-8.1.16.v20140903.jar:8.1.16.v20140903]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
15:38:31.980 [qtp665564874-31] WARN  APPLICATION AUDITOR - ###VolumeService.updateVolumes Executed in [63954] ms. ###

**Comment by benas** [comment]
@careerscale I give you a complete working example in #68
